### ISSUE TITLE
Remove obsolete request headers

### ISSUE THREAD

**Issue by rememberthemer** [jesus2099/konami-command#160]
fails under chrome and firefox

The test at lines 180-186 evaluates to FALSE because:

`this.responseText.indexOf('<a href="' + MBS + '/recording/' + from.getAttribute("ref") + '">') == -1`
`this.responseText.indexOf('<a href="' + MBS + '/recording/' + to.getAttribute("ref") + '">') == -1`

i.e. the urls are not in `this.responseText`
Interestingly the script works fine if these 2 tests are commented out, so all the required data are being retrieved.

Another issue is that
`208  xhr.setRequestHeader("Content-length", params[step].length);`
`209  xhr.setRequestHeader("Connection", "close");`
throw js warnings/error messages.
Apparently manually setting "Content-length" and "Connection" is forbidden. Commenting them out does not appear to affect functionality.

**Comment by jesus2099** [comment]
Incidentally I have noticed the same thing this morning and I have fixed this in ea57474c2e8c01cfbfd92539b48bd00072a57925. :)

For the record, commenting out these tests leads to « _we dont’ know if the merge/queue failed or passed_ » (and it regularly fails when MB server is over used) so this check must stay. :)

I keep this ticket open to check why I included those headers (just warnings in some browsers as they were deprecated at some point but are still required for some other browsers, IIRC).

**Comment by rememberthemer** [comment]
Cool. I don't actually know any js but would it be easier for your maintenance workloads to make those tests using a regex? I.e to deal with tiny server/schema changes.

FYI the Chrome jscript engine refuses to execute those header set lines.

Thanks for the script - has saved me **MANY** hours.

**Comment by jesus2099** [comment]
By experience, using strict code that breaks as soon as server code changes proved more reliable for MB user scripts.

It happened that, when I used more flexible code, the server changed and the script would go on as it did not change and could queue some wrong edits (in the worst case) or it could be difficult for me to find what’s wrong when it acts half good half weird. :)

What I am doing progressively is using Web Service instead of HTML page parsing.
But there is still some work to do in this area.
I am also thinking about making some MB specific libraries to share between scripts and so that a change would be necessary only in one place, in theory at least. ;)

This change was not pushed yet maybe, but you do have a work around in the mean time.

**Comment by jesus2099** [comment]
The link to fix was not understood by github as it was not yet pushed, here it is again: ea57474c2e8c01cfbfd92539b48bd00072a57925.

I have also removed those lines, we will see if it breaks someone and restore them if so.

```javascript
	xhr.setRequestHeader("Content-length", params[step].length);
	xhr.setRequestHeader("Connection", "close");
```

If nothing breaks, I will try to remember to do it for other scripts that use that (**jasrac-mb-minc_WORK-IMPORT-CROSS-LINKING**, **mb_INLINE-STUFF** and **mb_POWER-VOTE**).

**Comment by jesus2099** [comment]
Nothing in MASS MERGE seems to have been broken by this header removal.
I will check if it is opportunate to remove them from **jasrac-mb-minc_WORK-IMPORT-CROSS-LINKING**, **mb_INLINE-STUFF** and **mb_POWER-VOTE** as well.

**Comment by jesus2099** [comment]
Let’s try removing that from the 3 remaining scripts.
