### ISSUE TITLE
Default autolink section headers are visible even for empty sections

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#206]
This half broken feature comes from #61.

**Comment by y-van-z** [comment]
I have work in progress to address this issue, it features:
- hierarchical reorganization of search links,
- localized titles of both sections and links,
- coffee machine implementation,
- configurable sections.

**Comment by jesus2099** [comment]
You are unbelievable.
Just in case, is it possible to put **hidden links back above search links** in #238?

**Comment by y-van-z** [comment]
Unfortunately, I did not find an easy way to do it. My plan is to make a separate `ul` for search links, that will then put hidden links back at the usual place.

**Comment by jesus2099** [comment]
OK I’kl see how it all looks when back on a good PC.

**Comment by y-van-z** [comment]
@jesus2099 you will be very welcome to test and review [this branch](https://github.com/y-van-z/konami-command/commits/all-shook-up-links/mb_ALL-LINKS.user.js)! :bowtie:

(Separate commits before the drop allow to test both old and new autolinks at the same time.)

**Comment by jesus2099** [comment]
It’s awesome!
I can’t wait to merge your two other PR and then… this! wow. :)
Do you need some help for keeping current default searches?

**Comment by y-van-z** [comment]
Thanks! I did not create a PR because of the two following regressions:
1. Dropped support for action-based links: It was mostly used to address charset issues. I hope that we can address this more simply: either with dedicated token or with additional item attribute.
2. Dropped all default links: I am not at ease with Asian languages. I hope that you can adapt/update your Japanese and other Asian stuff to the proposed organization of links.
3. This is a big chunk of changes that requires time to review/test before adding too many links.

**Comment by jesus2099** [comment]
Wait for #244.
