### ISSUE TITLE
Display track artist(s) even if same as recording artist(s)

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#289]
I should display track AC each time it is different from release AC, even when it is the same as recording AC.

But, if I remember correctly, it was not my choice to not display it, it was because the Web Service would only return track AC when it is different from recording AC, or something like that.

Example: [HANG ON TO YOURSELF](https://musicbrainz.org/recording/82fb81a1-08c6-44e4-b71e-264dfc166b98), from [Edit #41082118](https://musicbrainz.org/edit/41082118).

**Comment by jesus2099** [comment]
And even no need to display track [AC] when it is same as release [AC].

It will be more natural to not display Onmyo-za below:

<img src="http://i.imgur.com/gHdlwgG.png">

**Comment by jesus2099** [comment]
It seems to match @culinkko’s #345 request about track artists.

> AC highlight on release page: I’d like to request an AC highlight on release pages whenever track AC doesn’t match the recording AC, similar way as when it’s displayed on recordings (currently in mb. INLINE TRACK ARTIST). The only question would be how to fit it in and also dealing with releases which don’t have the Artist column (releases where all tracks match the release AC), in which case you could position the artist name near the rating column. This is my mockup how it could look like for both types of releases: http://imgur.com/a/ZQCeJ.
> ![p0qPP4W.png](https://i.imgur.com/p0qPP4W.png)
> ![KcQVEas.png](https://i.imgur.com/KcQVEas.png)

**Comment by jesus2099** [comment]
But see if I shouldn’t merge #129 first.

**Comment by culinko** [comment]
I appreciate you very much for fixing the script! However the request you quoted was about the release page, not the recording page. Therefore I have some issues with the two newest changes:

I personally don't like showing the track artist credit on the recording page if it doesn't match the release artist credit because it suggests that there are errors even if there aren't. For example if you currently look at https://musicbrainz.org/recording/4d4a2962-c833-4bfe-b3d0-6bfe7f2bc89a , if there was one incorrect artist credit among all of them, you wouldn't know which one is the incorrect one because all of them are currently highlighted.

I also don't like not showing track AC if it matches the release AC regardless if the recording AC is different or not. Many times an editor fixes the recording AC (let's say adds a featuring artist), but they don't change the track AC. With this change you won't notice that something is still incorrect because the track AC would match the release AC.

Could you please make the following two changes as options? I would be very grateful for that.

**Comment by jesus2099** [comment]
Hello @culinko.
Let’s analyse this.
I use the Release artist cell to display Track artist when it is different from Release artist.

In your example, all tracks have a different AC than their releases, it’s why they are all highlighted.
To let me understand what you mean, which row would have you liked not highlighted in [your example](https://musicbrainz.org/recording/4d4a2962-c833-4bfe-b3d0-6bfe7f2bc89a)?

I am not highlighting right or wrong stuff. I am only highlighting hidden stuff that differs from what is shown.

**Comment by jesus2099** [comment]
> I also don't like not showing track AC if it matches the release AC regardless if the recording AC is different or not. Many times an editor fixes the recording AC (let's say adds a featuring artist), but they don't change the track AC. With this change you won't notice that something is still incorrect because the track AC would match the release AC.

We already see without this script when Recording artist differs from Release artists.
With the script it’s the same. If you see Recording artist differs from Release artists and there is no funny Track artist shown, it means that Recording an Track have different artist.

In most cases, Track and Release artists are the same, it is a pity to clutter the display with duplicate info…

Or what could be done is to apply span.name-variation on Track and Release artists that don’t match Recording artists…

I think we should discuss that in a new ticket…

**Comment by culinko** [comment]
When viewing my example recording, I would like to have nothing highlighted, because the track AC matches the recording AC like in the previous version of your userscript.

Basically:

track AC matches recording AC - show nothing
track AC doesn't match recording AC - show track AC

I personally don't care whether the release AC is different from track/recording because it happens too often (when featuring artist appears on track, on VA albums, etc.).

**Comment by jesus2099** [comment]
> When viewing my example recording, I would like to have nothing highlighted, because the track AC matches the recording AC **like in the previous version of your userscript.**

Please try [this version](https://github.com/jesus2099/konami-command/blob/ea7ad8413314701f763d92c39d93eca5310a00ca/mb_INLINE-TRACK-ARTIST.user.js).
It’s the last version (ea7ad8413314701f763d92c39d93eca5310a00ca) before I changed any rules of when to (not) display track AC (current latest f539683000956f1a604c0fe8d0545f77f3e727d4).

I think it’s what you call previous version and I do see track AC everywhere too.
I don’t remember having compared Recording and Track AC to decide whether I show or hide.
Maybe it’s an MBS change?
I’m only showing hidden stuff, not highlight diff. If I did highlight diff I would do with the diff style (span.name-variation) but would not add track AC if same as Release AC anyway, as it’s the Release AC cell. But the Release AC cell would also get the diff style.

Please also give the script latest version a few days try as I am rather in favour of least added content (clutter).

**Comment by culinko** [comment]
Even with the version you linked, the recording from my example still shows all track ACs, so I guess it has to be a mb change? I 100% remember that in the past (before the AC on mb was broken) I had only seen the track AC if it was different from the recording AC. If it was the same, the cell would not be shown. This is the behavior I wish would be available somehow...
