### ISSUE TITLE
VIAF links are shown duplicate in hidden links

### ISSUE THREAD

**Issue by Freso** [jesus2099/konami-command#293]
VIAF links are parsed and displayed in the sidebar by MusicBrainz' server code, but mb. ALL LINKS still show them again in the hidden links.

See https://beta.musicbrainz.org/artist/8643c935-fe75-41da-b6c0-a9bf2d23c7d8

**Comment by jesus2099** [comment]
Thanks for the ticket, @Freso, it is needed as I think it is the same problem as the ASIN link showing in hidden links a well, it is since MB is also HTTPS.
And it can also be that some URL are sorted https or http but are displayed the other.
My comparison must become protocol independent.
I am not on a computer right now but I guess it is that problem. ☺

**Comment by jesus2099** [comment]
This line of code is supposed to take care of this, but apparently, it doesn’t (always)? work:
https://github.com/jesus2099/konami-command/blob/59ab9a1aff8796704db10872526d3eae0e501632/mb_ALL-LINKS.user.js#L488

**Comment by jesus2099** [comment]
OK I understood, @Freso.
I cannot do much, MBS is storing VIAF URL as:

    http://viaf.org/viaf/307268363

but displays it with two changes, as:

    https://viaf.org/viaf/307268363/

My script will recognise http/https URLs as the same but the trailing slash difference, no.
I don’t know if I should add this as minimal change in my fuzzy comparison…
