### ISSUE TITLE
Ranked vote total sum doesn’t match MB Statistics page

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#383]
Ranked total votes is not just yes plus no votes, apparently.

**Comment by Freso** [comment]
It also includes approves, but it shouldn't include abstains. Does it? Keep in mind that all statistics are calculated once per day, so if someone cast a vote 7*24 hours minus 5 minutes before the stats are calculated, the stats will be outdated/"wrong" 5 minutes later. The user/profile page reflects the time of the loading, so that page can show different numbers than the /statistics/editors page.

**Comment by jesus2099** [comment]
Oh I forgot to say but I did included approvals in my ranked total.
I took jpmoss in https://musicbrainz.org/statistics/editors who has not voted for months. The total is less than their yes+no+appr.
And it seems that it is no longer updated.

**Comment by jesus2099** [comment]
I have to revert my commit as I really think it’s an MBS bug: https://tickets.metabrainz.org/browse/MBS-9651

**Comment by jesus2099** [comment]
I will revert 3403ad03dff7a4fa3afd8a67f38d142571bd1a3d with the [approximate](https://tickets.metabrainz.org/browse/MBS-9651) link.

**Comment by jesus2099** [comment]
This issue is on hold.
It can be closed when MBS-9651 is fixed, by removing my reference to this ticket and removing the **theoritical** wording.

**Comment by jesus2099** [comment]
I can close it as I already have the MBS-9651 appearing in profile pages to remind me this regularly.
