### ISSUE TITLE
Make EASY_DATE (more?) compatible with Paste-A-Date

### ISSUE THREAD

**Issue by Freso** [jesus2099/konami-command#40]
https://bitbucket.org/96187/userscripts/src/master/paste-a-date/

Currently if you have both activated and you copy a date into the paste-a-date text field, EASY_DATE will put the month in the year field and the day in the month field, removing the year entirely.

**Comment by jesus2099** [comment]
I will see what I can do in #20 without having some specific code but actually I do already use `input[placeholder='YYYY']`, `input[placeholder='MM']` and `input[placeholder='DD']` `querySelector`s to find MBS fields.
If Paste‐a‐date would do the same instead of looking for 1st, 2nd and 3rd fields, they would be compatible.
 
I would disable either EASY_DATE or Paste‐a‐date. :)

**Comment by Freso** [comment]
Yes, I have disabled EASY_DATE (since Paste-A-Date can deal with "human language" date specifications, which is what I more often come across).

**Comment by jesus2099** [comment]
Hi @Freso.
I made a change that should enable simultaneous use of Paste-A-Date or any other date related script.
But I didn't find a working version of Paste-A-Date! to test... :-/
