### ISSUE TITLE
TRACKLIST_TOOLS needs updating for MBS-10726

### ISSUE THREAD

**Issue by reosarevok** [jesus2099/konami-command#576]
Hi! MBS-10726, specifically https://github.com/metabrainz/musicbrainz-server/pull/2010/commits/d2255bd23d4c3b850f0c6cc2ef885aab33c8c174, changed some selectors from -disc to -medium (since they're not only for discs but for all sort of mediums). This is in beta now, and breaks TRACKLIST_TOOLS (at least) since that looks for `advanced-disc`, which is now `advanced-medium`.

**Comment by jesus2099** [comment]
Thank you very much, @reosarevok!
I see it will impact:

- `advanced-disc` indeed in TRACKLIST_TOOLS / mb_SUPER-MIND-CONTROL-II-X-TURBO
- `disc-format` in mb_HIDE-DIGITAL-RELEASES
- I also use `disc` links in mb_MASS-MERGE-RECORDINGS, it seems [they are not changed yet](https://tickets.metabrainz.org/browse/MBS-10726?focusedCommentId=58287&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-58287), though

**Comment by jesus2099** [comment]
@reosarevok, on average, how long do changes stay on beta and not on main?
How frequent are main server updates? Once a month?

**Comment by kellnerd** [comment]
@jesus2099 For now I have simply [added both selectors to my Unicode punctuation userscript](https://github.com/kellnerd/musicbrainz-bookmarklets/commit/b4549bd302698f71c77914da6ae47e912055e625#diff-7916cd4c7cfd6a9fb3f0f71f2971ca261c064238d41359e8f7e4e52b8fa30f8b) in order to make it already work on beta but still ensure compatibility with the production server. I will then remove the old selector after the next release.
The bookmarklets, on the other hand, got the full update at once, as people who use them have to come and look for an updated version themselves in any case as soon as the old version will be broken for them.

**Comment by reosarevok** [comment]
In general, a week or so, sometimes a bit more. We try to release a production update every two weeks, but sometimes it's three.

**Comment by jesus2099** [comment]
Thanks for the answers. :)

@kellnerd, yes I used to do that in the past, before focusing only on main, to save time. ;)
