### ISSUE TITLE
remove style from script

### ISSUE THREAD

**Issue by jerry-sileon** [jesus2099/konami-command#825]
I would suggest removing any styles from the script. Functionality and UI should be separated, so style scripts (dark mode etc.) can focus on the UI part. There are several places in the script where elements are added with hard-coded styles. These should be removed, replaced by the css variables that are already available in the MB style (although there are not a lot yet) or existing classes. This also applies to the settings page which is quite unreadable when MusicBrainz Dark is installed, for example.

**Comment by jesus2099** [comment]
Thank you for this ticket. 
Could you add some pictures of the culprit elements? 

I don't think I can use variable because I guess, but didn't check yet, that they are some `.less` variables, that are later converted to `.css` values, at run time. 

But I can use MB classes.
I usually do so, but mostly in more recent scripts and also I don't use a dark mode CSS.
Do I didn't include these tests in my mind, yet.

**Comment by kellnerd** [comment]
FWIW, this is how the settings look like with my userstyle companion:
![image](https://github.com/jesus2099/konami-command/assets/52860029/db7aa2a4-6db5-4883-b556-3824f85d88df)
But I have to [use `!important` a lot to make some userscript elements readable](https://github.com/kellnerd/userstyles/blob/a617d86da39526050c847e77d2b058ea39ca62b0/musicbrainz-userscripts-dark.user.css#L69) at all. Maybe these are a good indicator where you can start looking for possible improvements.

**Comment by jesus2099** [comment]
Thanks @kellnerd,
I didn't find those css variables like `--background-accent`.
Neither in my devtools (F12) nor in https://github.com/search?q=repo%3Ametabrainz%2Fmusicbrainz-server%20background-accent&type=code
Where are they? :)
I'm sure I didn't search well enough...

**Comment by kellnerd** [comment]
Oh sorry, these are [only defined in my userstyle](https://github.com/kellnerd/userstyles/blob/a617d86da39526050c847e77d2b058ea39ca62b0/musicbrainz-dark.user.css#L18), I should have mentioned that. I don't think MBS makes use of CSS variables in its bundled CSS currently.

**Comment by jesus2099** [comment]
It is important that userscript content is not confused with genuine MBS content.
Otherwise, people could think MBS is very buggy, once an obsolete userscript starts acting weird.
And otherwise, people could take some userscript data for granted, although they be wrong.
So I will usually not use MBS standard styles.

And I don't think there are MBS style variables that userscripts can use.
But if so, or if you have another suggestion, please let me know and I will reopen the ticket. :)
