### ISSUE TITLE
Long touch to force all votes does not change any votes

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#873]
I am on https://musicbrainz.org/release/25ce69f4-9703-4e74-92e9-381cfa35f1ed/open_edits containing 9 open edits with 7 Yes and 1 None. 
Long touch on Abstain does not change any votes or non-votes!

POWER VOTE version `2024.9.21`

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the shortcut function to properly handle long touch events on touch screens, ensuring that the Abstain button and other vote buttons work correctly with long touch gestures.

I also created pull request: https://github.com/jesus2099/konami-command/pull/874


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by kellnerd** [comment]
WTF, I just a got an email notification from GH about an AI bot trying to fix this issue 😂
Did you delete the PR and the comment or was it already gone when you looked?

**Comment by jesus2099** [comment]
I don't think it's usually possible to delete our stuff like this. 
Maybe the user/bot got banned from GitHub?

I did see its PR and everything, a few hours ago. 
I came back now to try its code, but it has indeed disappeared, silver then! 😅

**Comment by jesus2099** [comment]
I remember the AI patch had more changes than my simple 5 character fix.
