### ISSUE TITLE
ELEPHANT EDITOR: Add an option to not remember by default

### ISSUE THREAD

**Issue by pankkake** [jesus2099/konami-command#97]
By default, ELEPHANT EDITOR remembers my note.
However, with my editing style, half of the time or more, I set not to remember the note, so it can become quite annoying.

I don't know how it could be presented, maybe an additional checkbox "remember the remember checkbox status".

**Comment by jesus2099** [comment]
I see…

For the record, this **remember** check‐box was introduced in version [`2012-03-23_1111`](http://userscripts-mirror.org/scripts/show/94629).
Before that, I guess that edit notes were all saved (quickly loosing important saves because of one‐off stray edit notes).
**remember** is checked when making edits and is unchecked when commenting on existing edits.

**WORK‐AROUND (tip)** for you : 
Instead of submitting your edit by <kbd>CTRL</kbd>+<kbd>ENTER</kbd> in the textarea, by clicking SUBMIT EDIT button or anything like that : 
:point_right: Use <kbd>SHIFT</kbd>-CLICK(:mouse:) on the **remember** check‐box (or label). It will both uncheck it and submit edit.

About this evolution request : 
* I think this box behaviour should remain unchanged when commenting on existing edits (default **off**).
* The status of this check‐box for new edits (instead of **on**) could be its previous status. :star: 

:star: I think I already tried this and that I was often forgetting to check it… but because, unlike you, not saving is less often than save, for me.

**Comment by jesus2099** [comment]
I made the change. Let’s see if it’s intuitive now. :)

**Comment by pankkake** [comment]
Great!

**Comment by jesus2099** [comment]
Using it a bit, it seems that if it is set to not remember, it shouldn’t restore the last saved edit note either, right ?

**Comment by jesus2099** [comment]
What would you think to have, instead of this **remember** checkbox, the choice between the normal **Enter edit** button and a new **Save edit note and enter edit** button next to it ?

( <kbd>Cancel</kbd> )   <kbd>Enter edit</kbd>   <kbd>Enter edit (remember edit note)</kbd>

**Comment by pankkake** [comment]
I think it would be better!

**Comment by jesus2099** [comment]
Maybe I should do this instead of wasting time on #723 and #752.

**Comment by jesus2099** [comment]
Reverted original title and description, now that there is an actual ticket for alternative submit button: #116.
